### ISSUE TITLE
UnicodeError on Ldap resolver

### ISSUE THREAD

**Issue by vbarahona** [privacyidea/privacyidea#2639]
Hi,

I'm trying privacyidea in my organization and its looks awesome. But found a problem.

Configuring a Microsoft AD works perfect but when trying to configure an Ldap (Oracle Identity Directory) I get the next error:

UnicodeError("Unable to convert type list to unicode: [(0, False, 4, b'1.2.840.113556.1.4.319'), (0, False, 1, True), (0, False, 4, b'0\\x84\\x00\\x00\\x00\\n\\x02\\x01\\x00\\x04\\x05853c3')]")

Any clue that what is going on?

Best regards.

**Comment by vbarahona** [comment]
My Privacyidea is running in a ubuntu 20.04 fresh install. Installed with apt from 

I have enabled debug logging:

[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:547] Policies after matching active: []
[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:547] Policies after matching scope: []
[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:572] Policies after matching action: []
[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:572] Policies after matching adminrealm: []
[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:572] Policies after matching adminuser: []
[2021-02-25 18:45:26,125][3737]••••••••••••[139740004189952][DEBUG][privacyidea.lib.policy:607] Policies after matching resolver: []
[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:619] Policies after matching pinode: []
[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:649] Policies after matching client: []
[2021-02-25 18:45:26,125][3737][139740004189952][DEBUG][privacyidea.lib.policy:198] Exiting list_policies with result []
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.policy:727] Policies after matching time: []
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.policy:732] Policies after matching conditions
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.policy:198] Exiting match_policies with result []
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.policy:185] Entering list_policies with arguments (<privacyidea.lib.policy.PolicyClass object at 0x7f17a7d85dc0>,) and keywords {'scope': 'admin', 'active': True}
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.policy:547] Policies after matching active: []
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.policy:547] Policies after matching scope: []
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.policy:198] Exiting list_policies with result []
[2021-02-25 18:45:26,126][3737][139740004189952][DEBUG][privacyidea.lib.resolver:185] Entering pretestresolver with arguments ('ldapresolver', {'AUTHTYPE': 'Simple', 'BINDDN': 'cn=admin,cn=Users,dc=org,dc=es', 'BINDPW': '__CENSORED__', 'CACHE_TIMEOUT': '120', 'EDITABLE': False, 'LDAPBASE': 'cn=Users,dc=org,dc=es', 'LDAPSEARCHFILTER': '(cn=*)(objectClass=inetorgperson)', 'LDAPURI': 'ldap://ldap.org.es', 'LOGINNAMEATTRIBUTE': 'cn', 'NOREFERRALS': True, 'NOSCHEMAS': True, 'SCOPE': 'SUBTREE', 'SERVERPOOL_PERSISTENT': False, 'SERVERPOOL_ROUNDS': '2', 'SERVERPOOL_SKIP': '30', 'SIZELIMIT': 0, 'START_TLS': False, 'TIMEOUT': '5', 'TLS_VERIFY': False, 'TLS_VERSION': '5', 'UIDTYPE': 'cod_persona', 'USERINFO': '{ "email" : "mail", "surname" : "sn", "givenname" : "nombre" }', 'type': 'ldapresolver', 'resolver': 'LDAP'}) and keywords {}
[2021-02-25 18:45:26,127][3737][139740004189952][DEBUG][privacyidea.lib.resolver:185] Entering get_resolver_list with arguments () and keywords {'filter_resolver_name': 'LDAP'}
[2021-02-25 18:45:26,127][3737][139740004189952][DEBUG][privacyidea.lib.resolver:200] Exiting get_resolver_list with result HIDDEN
[2021-02-25 18:45:26,127][3737][139740004189952][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:173] Get LDAP schema info: 'NO_INFO'
[2021-02-25 18:45:26,127][3737][139740004189952][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:869] Added ldap.uam.es, None, False to server pool.
[2021-02-25 18:45:27,015][3737][139740004189952][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:1054] Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 1031, in testconnection
    for entry in ignore_sizelimit_exception(l, g):
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 188, in ignore_sizelimit_exception
    last_entry = next(generator)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/extend/standard/PagedSearch.py", line 56, in paged_search_generator
    result = connection.search(search_base,
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/core/connection.py", line 846, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/sync.py", line 139, in post_send_search
    responses, result = self.get_response(message_id)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/base.py", line 354, in get_response
    responses = self._get_response(message_id, timeout)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/sync.py", line 165, in _get_response
    dict_response = self.decode_response_fast(ldap_resp)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/base.py", line 536, in decode_response_fast
    result = ldap_result_to_dict_fast(ldap_message['payload'])
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/utils/asn1.py", line 179, in ldap_result_to_dict_fast
    response_dict['referrals'] = referrals_to_list([to_unicode(referral[3], from_server=True) for referral in response[3][3]])  # referrals
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/utils/asn1.py", line 179, in <listcomp>
    response_dict['referrals'] = referrals_to_list([to_unicode(referral[3], from_server=True) for referral in response[3][3]])  # referrals
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/utils/conv.py", line 75, in to_unicode
    raise UnicodeError("Unable to convert type %s to unicode: %r" % (obj.__class__.__name__, obj))
UnicodeError: Unable to convert type list to unicode: [(0, False, 4, b'1.2.840.113556.1.4.319'), (0, False, 1, True), (0, False, 4, b'0\x84\x00\x00\x00\n\x02\x01\x00\x04\x05853c3')]

[2021-02-25 18:45:27,018][3737][139740004189952][DEBUG][privacyidea.lib.resolver:198] Exiting pretestresolver with result (False, 'UnicodeError("Unable to convert type list to unicode: [(0, False, 4, b\'1.2.840.113556.1.4.319\'), (0, False, 1, True), (0, False, 4, b\'0\\\\x84\\\\x00\\\\x00\\\\x00\\\\n\\\\x02\\\\x01\\\\x00\\\\x04\\\\x05853c3\')]")')
[2021-02-25 18:45:27,020][3737][139740004189952][DEBUG][privacyidea.api.resolver:198] Exiting test_resolver with result <PiResponseClass 414 bytes [200 OK]>
[2021-02-25 18:45:27,042][3737][139740004189952][DEBUG][privacyidea.api.before_after:100] End handling of request '/resolver/test?'

Has make any sense?

Regards.

**Comment by plettich** [comment]
Thanks for the report. Could You try to use a more recent version of the ldap3 package?
According to the [changelog](https://github.com/cannatag/ldap3/blob/dev/CHANGES.txt) they fixed some conversion of the ObjectGUID which might apply here.
You can do this by activating the python virtualenv and installing the package:
```
$ source /opt/privacyidea/bin/activate
$ pip install -U ldap3
$ systemctl restart apache2
```

**Comment by vbarahona** [comment]
Hi,
Thanks for the answer. I tried you instructions:

 ```
# source /opt/privacyidea/bin/activate
(privacyidea) # pip install -U ldap3
Collecting ldap3
  Downloading ldap3-2.9-py2.py3-none-any.whl (430 kB)
     |████████████████████████████████| 430 kB 2.4 MB/s 
Requirement already satisfied, skipping upgrade: pyasn1>=0.4.6 in /opt/privacyidea/lib/python3.8/site-packages (from ldap3) (0.4.8)
Installing collected packages: ldap3
  Attempting uninstall: ldap3
    Found existing installation: ldap3 2.8.1
    Uninstalling ldap3-2.8.1:
      Successfully uninstalled ldap3-2.8.1
Successfully installed ldap3-2.9
(privacyidea) # systemctl restart apache2
```

but I get same error:

```
[2021-03-14 17:11:35,372][1784][140555729430272][DEBUG][privacyidea.lib.policy:547] Policies after matching active: []
[2021-03-14 17:11:35,372][1784][140555729430272][DEBUG][privacyidea.lib.policy:547] Policies after matching scope: []
[2021-03-14 17:11:35,372][1784][140555729430272][DEBUG][privacyidea.lib.policy:572] Policies after matching action: []
[2021-03-14 17:11:35,372][1784][140555729430272][DEBUG][privacyidea.lib.policy:572] Policies after matching adminrealm: []
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:572] Policies after matching adminuser: []
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:607] Policies after matching resolver: []
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:619] Policies after matching pinode: []
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:649] Policies after matching client: []
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:198] Exiting list_policies with result []
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:727] Policies after matching time: []
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:732] Policies after matching conditions
[2021-03-14 17:11:35,373][1784][140555729430272][DEBUG][privacyidea.lib.policy:198] Exiting match_policies with result []
[2021-03-14 17:11:35,374][1784][140555729430272][DEBUG][privacyidea.lib.policy:185] Entering list_policies with arguments (<privacyidea.lib.policy.PolicyClass object at 0x7fd5a4ea29d0>,) and keywords {'scope': 'admin', 'active': True}
[2021-03-14 17:11:35,374][1784][140555729430272][DEBUG][privacyidea.lib.policy:547] Policies after matching active: []
[2021-03-14 17:11:35,374][1784][140555729430272][DEBUG][privacyidea.lib.policy:547] Policies after matching scope: []
[2021-03-14 17:11:35,374][1784][140555729430272][DEBUG][privacyidea.lib.policy:198] Exiting list_policies with result []
[2021-03-14 17:11:35,374][1784][140555729430272][DEBUG][privacyidea.lib.resolver:185] Entering pretestresolver with arguments ('ldapresolver', {'AUTHTYPE': 'Simple', 'BINDDN': 'cn=admin,cn=Users,dc=org,dc=es', 'BINDPW': '__CENSORED__', 'CACHE_TIMEOUT': '120', 'EDITABLE': False, 'LDAPBASE': 'cn=Users,dc=org,dc=es', 'LDAPSEARCHFILTER': '(cn=*)(objectClass=inetorgperson)', 'LDAPURI': 'ldap://ldap.org.es', 'LOGINNAMEATTRIBUTE': 'cn', 'NOREFERRALS': True, 'NOSCHEMAS': False, 'SCOPE': 'SUBTREE', 'SERVERPOOL_PERSISTENT': True, 'SERVERPOOL_ROUNDS': '2', 'SERVERPOOL_SKIP': '30', 'SIZELIMIT': 0, 'START_TLS': False, 'TIMEOUT': '5', 'TLS_VERIFY': False, 'TLS_VERSION': '5', 'UIDTYPE': 'cod_persona', 'USERINFO': '{ "email" : "mail", "surname" : "sn", "givenname" : "nombre" }', 'type': 'ldapresolver', 'resolver': 'LDAP'}) and keywords {}
[2021-03-14 17:11:35,374][1784][140555729430272][DEBUG][privacyidea.lib.resolver:185] Entering get_resolver_list with arguments () and keywords {'filter_resolver_name': 'LDAP'}
[2021-03-14 17:11:35,375][1784][140555729430272][DEBUG][privacyidea.lib.resolver:200] Exiting get_resolver_list with result HIDDEN
[2021-03-14 17:11:35,375][1784][140555729430272][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:173] Get LDAP schema info: 'SCHEMA'
[2021-03-14 17:11:35,375][1784][140555729430272][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:869] Added ldap.org.es, None, False to server pool.
[2021-03-14 17:11:36,957][1784][140555729430272][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:1054] Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 1031, in testconnection
    for entry in ignore_sizelimit_exception(l, g):
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 188, in ignore_sizelimit_exception
    last_entry = next(generator)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/extend/standard/PagedSearch.py", line 56, in paged_search_generator
    result = connection.search(search_base,
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/core/connection.py", line 853, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/sync.py", line 178, in post_send_search
    responses, result = self.get_response(message_id)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/base.py", line 355, in get_response
    responses = self._get_response(message_id, timeout)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/sync.py", line 204, in _get_response
    dict_response = self.decode_response_fast(ldap_resp)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/base.py", line 537, in decode_response_fast
    result = ldap_result_to_dict_fast(ldap_message['payload'])
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/utils/asn1.py", line 179, in ldap_result_to_dict_fast
    response_dict['referrals'] = referrals_to_list([to_unicode(referral[3], from_server=True) for referral in response[3][3]])  # referrals
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/utils/asn1.py", line 179, in <listcomp>
    response_dict['referrals'] = referrals_to_list([to_unicode(referral[3], from_server=True) for referral in response[3][3]])  # referrals
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/utils/conv.py", line 75, in to_unicode
    raise UnicodeError("Unable to convert type %s to unicode: %r" % (obj.__class__.__name__, obj))
UnicodeError: Unable to convert type list to unicode: [(0, False, 4, b'1.2.840.113556.1.4.319'), (0, False, 1, True), (0, False, 4, b'0\x05\x02\x01\x00\x04\x00')]

[2021-03-14 17:11:36,958][1784][140555729430272][DEBUG][privacyidea.lib.resolver:198] Exiting pretestresolver with result (False, 'UnicodeError("Unable to convert type list to unicode: [(0, False, 4, b\'1.2.840.113556.1.4.319\'), (0, False, 1, True), (0, False, 4, b\'0\\\\x05\\\\x02\\\\x01\\\\x00\\\\x04\\\\x00\')]")')
[2021-03-14 17:11:36,959][1784][140555729430272][DEBUG][privacyidea.api.resolver:198] Exiting test_resolver with result <PiResponseClass 383 bytes [200 OK]>
[2021-03-14 17:11:36,979][1784][140555729430272][DEBUG][privacyidea.api.before_after:100] End handling of request '/resolver/test?'
```

Is there anything else I can try?

Regards.

**Comment by plettich** [comment]
Hi @vbarahona thanks for testing this, we'll look into this.

**Comment by laclaro** [comment]
@plettich is this resolved by #2670?

**Comment by vbarahona** [comment]
Hi @plettich,

Not in my case.

I have updated to privacyidea 3.6.2 (from 3.6.1). Upgrade ldap3 from 2.9 to 2.9.1.

But the error persists.
UnicodeError: Unable to convert type list to unicode: [(0, False, 4, b'1.2.840.113556.1.4.319'), (0, False, 1, True), (0, False, 4, b'0\x05\x02\x01\x00\x04\x00')]

Could this be related with ldap pagination?

Regards

**Comment by jona-samuel** [comment]
Mabey this will be fixed by #3753

**Comment by plettich** [comment]
> Mabey this will be fixed by #3753

@jona-samuel probably not since that issue is specific for Oracle databases, not the Oracle Directory Service (LDAP).

**Comment by plettich** [comment]
This is a pretty old issue and it looks like the Oracle Identity Directory returns data not conforming with the LDAP standard (at some point the ldap3 module expects a string but receives a list of values).
Without access to an Oracle  Identity Provider we are unable to reproduce this issue (and if we would be able to, it is probably better suited in the [`ldap3`](https://github.com/cannatag/ldap3/) package (i couldn't find a matching issue there).
Closing this for now.
