### ISSUE TITLE
Unable to login as admin on fresh install ubuntu 20.04

### ISSUE THREAD

**Issue by cdpiazza** [privacyidea/privacyidea#3100]
### Top-level intent

What did you try to achieve?
Im triying to login with an admin user after a fresh install on ubuntu 20.04 from .deb sources.

### Steps to reproduce

1. Install ubuntu 20.04
2. Follow procedure of https://privacyidea.readthedocs.io/en/latest/installation/ubuntu.html#install-ubuntu
3. Create admin user with pi-manage
4. Try to login on webUI

### Expected outcome

What do you think, how the system should have worked?

Login achieved

### Actual outcome

What did actually happen?

×Fallo en la autenticación. 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### Configuration

* **3.7**:
* **Ubuntu packages**: (from Ubuntu packages, github, PyPI, ...)
* **Python 3.8.10**:
* **Ubuntu 20.04**:
* **Apache2**:
* **MySQL**: (MySQL, PostgreSQL, ...)

### Log file
[log.txt](https://github.com/privacyidea/privacyidea/files/8484034/log.txt)

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by cornelinux** [comment]
The package seems to be built with python 3.8 while 20.04 ships 3.10?

**Comment by cdpiazza** [comment]
Well, i can confirm that it is a problem with the spanish translation.

I tried exaclty the same instalation but with a browser in english and i can login correctly with the admin.

Is there a way to disable the automatic translation of the site in order to use always the english version no matter what config the browser is in?

**Comment by cornelinux** [comment]
This is fixed in https://github.com/privacyidea/privacyidea/pull/3106/commits/cdc7e878e3fd3c802576d134f13e67243f13211d

We will try to publish this in 3.7.1.

**Comment by cdpiazza** [comment]
The error persists in version 3.7.2 after the update.

[2022-07-06 11:18:44,323][2985][140601313879936][INFO][privacyidea.lib.pooling:84] Creating a new engine and connection pool for key sql.aaad68415de87df4e013602c912c1c7d25f6d65a
[2022-07-06 11:18:44,324][2985][140601313879936][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string sqlite://///etc/privacyidea/users.sqlite
[2022-07-06 11:18:44,345][2985][140601313879936][INFO][privacyidea.lib.resolvers.LDAPIdResolver:322] Setting system wide POOLING_LOOP_TIMEOUT to 10.
[2022-07-06 11:18:45,459][2985][140601313879936][INFO][privacyidea.api.auth:289] Local admin 'soporte' successfully logged in.
[2022-07-06 11:18:45,461][2985][140601313879936][INFO][privacyidea.lib.crypto:829] initializing HSM class: <class 'privacyidea.lib.security.default.DefaultSecurityModule'>
[2022-07-06 11:18:45,461][2985][140601313879936][INFO][privacyidea.lib.crypto:268] Initialized HSM object {'obj': <privacyidea.lib.security.default.DefaultSecurityModule object at 0x7fe04642d3d0>}
[2022-07-06 11:18:45,470][2985][140601313879936][ERROR][privacyidea.app:1891] Exception on /auth [POST]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
    return wrapped_function(*args, **kwds)
  [Previous line repeated 1 more time]
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  [Previous line repeated 3 more times]
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/event.py", line 100, in event_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/auth.py", line 350, in get_auth_token
    rights = g.policy_object.ui_get_rights(role, realm, loginname,
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/policy.py", line 1196, in ui_get_rights
    rights = get_static_policy_definitions(scope)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/policy.py", line 2284, in get_static_policy_definitions
    'desc': _("Allow the user to authenticate (default). If set to '{0!s}', "
ValueError: expected ':' after conversion specifier

**Comment by plettich** [comment]
Hi @cdpiazza 
sorry, the automatic update of the spelling files wasn't integrated into the release branch.
You can mitigate this by copying the files [`messages.mo`](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/translations/es/LC_MESSAGES/messages.mo?raw=true) and [`messages.po`](https://raw.githubusercontent.com/privacyidea/privacyidea/master/privacyidea/translations/es/LC_MESSAGES/messages.po) into `/opt/privacyidea/lib/python3.8/site-packages/privacyidea/translations/es/LC_MESSAGES/`

**Comment by cdpiazza** [comment]
Ok, now its working. Thank you. Hope to see it on stable soon.

**Comment by EchedeyLR** [comment]
Hi.

Is this solved in the release branch of 3.7.3?

**Comment by pablo-knight** [comment]
Hi @EchedeyLR,

is fixed, look on our changelog:
https://github.com/privacyidea/privacyidea/blob/v3.7.3/Changelog

**Comment by EchedeyLR** [comment]
Thank you @pablo-knight:
May I ask if you have a way to sponsor the project like OpenCollective or LiberaPay?

**Comment by plettich** [comment]
> Thank you @pablo-knight: May I ask if you have a way to sponsor the project like OpenCollective or LiberaPay?

You could buy support for privacyIDEA from [NetKnights](https://netknights.it/), the company that develops privacyIDEA...
