### ISSUE TITLE
After upgrade there are LDAPresolver errors

### ISSUE THREAD

**Issue by wszychta** [privacyidea/privacyidea#732]
# What did you try to do?
I wanted to upgrade privacyIDEA from version 2.11.3 to newest 2.19 or 2.18.1 version. I did everything as written in this website: http://privacyidea.readthedocs.io/en/latest/installation/upgrade.html but after upgrading I discovered problems with ldapresolver

# What outcome did you expect?

**What do you think, how the system should have worked?**

Update should work without any problem.

**What did acutally happen?**

Users from Active directory are not able to log via VPN because of errors. The second issue is that privacyIDEA is running after update in debug mode, but in config file is still set to INFO.

# Configuration

* privacyIDEA Version: 2.11.3 -> 2.19

* Installation method: pip install in virtualenv

## more details: 

* OS: CentOS 7

* Webserver: HTTPD 2.4.6-31.el7

* Tokendatabase: 5.5.44-MariaDB

# Log file

**Update LOG**
[update.txt](https://github.com/privacyidea/privacyidea/files/1101630/update.txt)
**Database update LOG**
[update_db.txt](https://github.com/privacyidea/privacyidea/files/1101639/update_db.txt)
**privacyidea.log**
`
[2017-06-26 11:30:14,202][3303][139998652352256][ERROR][privacyidea.lib.token:424] User information can not be retrieved: 'ascii' codec can't encode character u'\u0144' in position 27: ordinal not in range(128)
[2017-06-26 11:30:14,202][3303][139998652352256][ERROR][privacyidea.lib.token:424] User information can not be retrieved: 'ascii' codec can't encode character u'\u0144' in position 27: ordinal not in range(128)
[2017-06-26 11:30:14,793][3303][139998652352256][ERROR][privacyidea.lib.token:424] User information can not be retrieved: 'ascii' codec can't encode character u'\u0144' in position 14: ordinal not in range(128)
[2017-06-26 11:30:14,793][3303][139998652352256][ERROR][privacyidea.lib.token:424] User information can not be retrieved: 'ascii' codec can't encode character u'\u0144' in position 14: ordinal not in range(128)
`

**Comment by cornelinux** [comment]
Might be related to #738 
@wszychta Can you please provide more information about your LDAP server?

Did you upgrade the whole pip directory?
Which ldap3 version are you using?

**Comment by wszychta** [comment]
Yes, I have upgraded whole pip directory and pip to last version.

ldap3 version is 2.2.4.

I have manage to update privacyIDEA by changing UID Type from CN to sAMAccountName, but some users with polish letters still cannot login to privacyIDEA website.

Here I have logs:
`[2017-07-04 14:11:01,176][26220][140002201675520][INFO][privacyidea.lib.user:346] User u'XXXXX.XXXXXX' from realm u'XXXXX' tries to authenticate
[2017-07-04 14:11:01,194][26220][140002201675520][WARNING][privacyidea.lib.resolvers.LDAPIdResolver:255] failed to check password for u'marta.kusinska'/u'CN=XXXXXX\xc5\x84X,OU=XXX,OU=XXX,DC=XXX,DC=XXX,DC=com': Exception('Wrong credentials',)
`

**Comment by cornelinux** [comment]
https://github.com/privacyidea/privacyidea/blob/v2.19/privacyidea/lib/token.py#L424

**Comment by wszychta** [comment]
I have changed code and change setting from sAMAccountName to DN.
Now all users have **resolver error** and log for all users is:
```
[2017-07-19 13:57:32,280][1988][140397892290304][ERROR][privacyidea.lib.token:424] User information can not be retrieved: attribute type not present
[2017-07-19 13:57:32,280][1988][140397892290304][ERROR][privacyidea.lib.token:424] User information can not be retrieved: attribute type not present
[2017-07-19 13:57:32,303][1988][140397892290304][ERROR][privacyidea.lib.token:424] User information can not be retrieved: attribute type not present
[2017-07-19 13:57:32,303][1988][140397892290304][ERROR][privacyidea.lib.token:424] User information can not be retrieved: attribute type not present
```

**Comment by cornelinux** [comment]
Can you please check the current master branch?
We added several fixes/changes to LDAP and logging regarding non-ascii characters.
I think your issue might be solved, too.
Thanks a lot!

**Comment by wszychta** [comment]
I have upgraded privacyIDEA to version 2.19.1 via PIP and problem still exists when I want retrive user via DN:
```
[2017-07-24 10:51:12,419][2421][140221373495040][ERROR][privacyidea.lib.token:426] User information can not be retrieved: attribute type not present
[2017-07-24 10:51:12,419][2421][140221373495040][ERROR][privacyidea.lib.token:426] User information can not be retrieved: attribute type not present
[2017-07-24 10:51:12,426][2421][140221373495040][ERROR][privacyidea.lib.token:426] User information can not be retrieved: attribute type not present
[2017-07-24 10:51:12,426][2421][140221373495040][ERROR][privacyidea.lib.token:426] User information can not be retrieved: attribute type not present
```

When I changed back sAMAccountName only users without Polish letters in name or surname are able to login to privacyIDEA.
This is the same problem with Polish letters. In logs I see that polish letter "ó" is \xc3\xb3
```
[2017-07-24 10:59:12,588][2421][140221194651392][WARNING][privacyidea.lib.resolvers.LDAPIdResolver:253] failed to check password for u'XXX.XXX'/u'CN=XXX XXX\xc3\xb3XXX,OU=People,OU=XXX,DC=XXX,DC=XXX,DC=XXX': Exception('Wrong credentials',)
```

**Comment by cornelinux** [comment]
You must not upgrade to 2.19.1 but to the master branch here at github. Lately we fixed several LDAP issues in regards to unicode. But these have not been released, yet.

**Comment by wszychta** [comment]
I have upgraded privacyIDEA to master branch and problem still exists.
I see that instalation is succeded except one error with FreeRADIUS files
```
error: can't copy 'authmodules/FreeRADIUS/LICENSE': doesn't exist or not a regular file
```
But after commenting lines 139,140 and 141 in setup.py file setup succeded.

But users with polish letters cannot login to site. Logs are the same as earlier.

**Comment by cornelinux** [comment]
I was not aware you are using radius.
Can you verify that the auth with privacyidea works fine and also provide the freeradius log?

This might be a problem in the freeradius plugin.

**Comment by wszychta** [comment]
I'm not using FreeRADIUS, only LDAP to authorize users.
This was only one part of setup process wihich I could skip for my installation.

**Comment by fredreichbier** [comment]
Hm, I got a bit confused about your setup. I assume you're on the current privacyIDEA master. Can users with polish letters be authenticated via privacyIDEA, i.e. does
<pre>curl https://privacyideaserver/validate/check?user=xxx&pass=yyy</pre> work?
What is the UID type of your LDAP resolver?
Do you have a ``otppin=userstore`` policy set?

**Comment by wszychta** [comment]
After testing curl I have:
```
"result": {"status": false, "error": {"message": "ERR905: Missing parameter: 'pass'", "code": 905}}
```
but in webbrowser I have different result:
```
"detail": {"message": "wrong otp pin", "threadid": 139908323153664}, "versionnumber": "2.20.dev0", "version": "privacyIDEA 2.20.dev0", "result": {"status": true, "value": false}, "time": 1501766075.972969, "id": 1}
```

Where I can find `otppin=userstore` policy?

**Comment by cornelinux** [comment]
Please test with

    curl 'https://privacyideaserver/validate/check?user=xxxx&pass=xxxx'

Or call the URL in your browser. The command line misinterprets the "&", thus the parameter "pass" is missing.

Ah, you see: In your webbrowser, you provided the wrong OTP pin, thinks privacyIDEA.
``otppin=userstore`` is a setting in the authentication policy.

**Comment by cornelinux** [comment]
For setting the authentication as administrator in the WebUI go to ``Config -> Policy`` and create a policy in scope **authentication** with action ``otppin=userstore``.

We will close this issue if we do not here anything till September 8th.

**Comment by wszychta** [comment]
After upgrading privacyIDEA to 2.20.dev3 I have created **authentication policy** and changed **otppin** to **userstore**

**The problem still exists.**

When I set UID Type to DN I have errors on all users (with and without Polish Letters):
`[2017-09-01 10:40:07,421][3161][140695669786368][ERROR][privacyidea.lib.token:429] User information can not be retrieved: attribute type not present
[2017-09-01 10:40:07,421][3161][140695669786368][ERROR][privacyidea.lib.token:429] User information can not be retrieved: attribute type not present`

Checking with curl gave me json:
` "detail": {"message": "The user has no tokens assigned", "threadid": 140695711749888}, "versionnumber": "2.20.dev3", "version": "privacyIDEA 2.20.dev3", "result": {"status": true, "value": false}, "time": 1504256129.679439, "id": 1}`
and log in system:
`[2017-09-01 10:55:29,654][3161][140695711749888][INFO][privacyidea.lib.user:230] user u'XXXXX' found in resolver u'ZZZZZ'
[2017-09-01 10:55:29,655][3161][140695711749888][INFO][privacyidea.lib.user:231] userid resolved to u'CN=XXXXX ZZZZZ\xc5\x84ZZZZ,OU=People,DC=CCCCC,DC=com'`

When I change to sAMAccountName users only with Polish Letters are not able to login:
`[2017-09-01 10:37:49,121][3161][140695694964480][INFO][privacyidea.lib.user:346] User u'XXXXXX' from realm u'XXXXX' tries to authenticate
[2017-09-01 10:37:49,126][3161][140695694964480][WARNING][privacyidea.lib.resolvers.LDAPIdResolver:255] failed to check password for u'XXXXX'/u'CN=XXXXX ZZZZZ\xc5\x84ZZZZ,OU=People,DC=CCCCC,DC=com': Exception('Wrong credentials',)`

json:
`"detail": {"message": "wrong otp pin", "threadid": 140695669786368}, "versionnumber": "2.20.dev3", "version": "privacyIDEA 2.20.dev3", "result": {"status": true, "value": false}, "time": 1504256648.155052, "id": 1}`
log:
`[2017-09-01 11:04:08,136][3161][140695669786368][WARNING][privacyidea.lib.resolvers.LDAPIdResolver:255] failed to check password for u'XXXXX'/u'CN=XXXXX ZZZZZ\xc5\x84ZZZZ,OU=People,DC=CCCCC,DC=com': Exception('Wrong credentials',)
[2017-09-01 11:04:08,137][3161][140695669786368][INFO][privacyidea.lib.user:359] user User(login=u'XXXXX', realm=u'ZZZZZ', resolver=u'ZZZZZ') failed to authenticate.`

**Comment by cornelinux** [comment]
I am still missing the traceback. There are several places where the ``Hanńs`` could break.

Please add the traceback log OR use version 2.20dev4, which contains the traceback. Set logging to debug, which will output the traceback to the logfile as mentioned on Jul 18th.

**Comment by fredreichbier** [comment]
I think there are multiple combined issues here:

Firstly, I think the reason for the "failed to check password" warnings could be that the AD is sending data in a non-standard encoding (i.e. something else than UTF-8) which causes privacyIDEA to resolve users to incorrect user IDs. Do you have a specific codepage setting on the AD machine? If this is indeed the problem, you can work around it by changing the UID type to an attribute which does not contain special characters, e.g. ``objectGUID``.

After having changed the UID type, you should restart the web server or wait for 5 minutes as there is a caching mechanism in place.

**Comment by wszychta** [comment]
I'm sending you Traceback from log. I have waited for ten minutes after restarting privacyIDEA each time I changed this parameter

When I set **objectGUID** I see this error:
`[2017-09-08 13:22:57,570][6929][140135673317120][DEBUG][privacyidea.lib.token:430] Traceback (most recent call last):
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/token.py", line 422, in get_tokens_paginate
    userobject = tokenobject.user
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/tokenclass.py", line 198, in user
    username = get_username(self.token.user_id, self.token.resolver)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/log.py", line 193, in log_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/usercache.py", line 63, in cache_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/user.py", line 693, in get_username
    username = y.getUsername(userid)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 454, in getUsername
    info = self.getUserInfo(user_id)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 165, in cache_wrapper
    f_result = func(self, *args, **kwds)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 401, in getUserInfo
    search_userId = to_unicode(self._trim_user_id(userId))
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 324, in _trim_user_id
    userId = trim_objectGUID(userId)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 121, in trim_objectGUID
    userId = uuid.UUID("{{{0!s}}}".format(userId)).bytes_le
  File "/usr/lib64/python2.7/uuid.py", line 134, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string`

When users with Polish letters are trying to login I see this error:
`[2017-09-08 13:51:30,741][7816][139720030119680][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:256] Traceback (most recent call last):
  File "/opt/privacyIDEA/lib/python2.7/site-packages/privacyIDEA-2.20.dev4-py2.7.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 250, in checkPass
    raise Exception("Wrong credentials")
Exception: Wrong credentials`
This error is in both cases (objectGUID and sAMAccountName).

**Comment by cornelinux** [comment]
This conversion does not seem to lead anywhere. The OP was not able to state his point and provide the necessary information.
